# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:39:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Driver(BaseModel):
    BirthDate: Optional[str] = None
    BirthPlace: Optional[str] = None
    Chassis: Optional[str] = None
    Created: Optional[str] = None
    CrewChief: Optional[str] = None
    DriverID: Optional[int] = None
    Engine: Optional[str] = None
    FirstName: Optional[str] = None
    Gender: Optional[str] = None
    Height: Optional[int] = None
    LastName: Optional[str] = None
    Manufacturer: Optional[str] = None
    Number: Optional[int] = None
    NumberDisplay: Optional[str] = None
    PhotoUrl: Optional[str] = None
    Sponsors: Optional[str] = None
    Team: Optional[str] = None
    Updated: Optional[str] = None
    Weight: Optional[int] = None


class DriverRace(BaseModel):
    Bonus: Optional[float] = None
    Created: Optional[str] = None
    CurrentPosition: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    DriverID: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FastestLaps: Optional[float] = None
    FinalPosition: Optional[float] = None
    Laps: Optional[float] = None
    LapsLed: Optional[float] = None
    Manufacturer: Optional[str] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    NumberDisplay: Optional[str] = None
    Penalty: Optional[float] = None
    Points: Optional[float] = None
    PoleFinalPosition: Optional[float] = None
    Poles: Optional[float] = None
    PositionDifferential: Optional[float] = None
    QualifyingSpeed: Optional[float] = None
    RaceID: Optional[int] = None
    Season: Optional[int] = None
    StartPosition: Optional[float] = None
    StatID: Optional[int] = None
    Updated: Optional[str] = None
    Wins: Optional[float] = None


class DriverRaceProjection(BaseModel):
    Bonus: Optional[float] = None
    Created: Optional[str] = None
    CurrentPosition: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    DriverID: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FastestLaps: Optional[float] = None
    FinalPosition: Optional[float] = None
    Laps: Optional[float] = None
    LapsLed: Optional[float] = None
    Manufacturer: Optional[str] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    NumberDisplay: Optional[str] = None
    Penalty: Optional[float] = None
    Points: Optional[float] = None
    PoleFinalPosition: Optional[float] = None
    Poles: Optional[float] = None
    PositionDifferential: Optional[float] = None
    QualifyingSpeed: Optional[float] = None
    RaceID: Optional[int] = None
    Season: Optional[int] = None
    StartPosition: Optional[float] = None
    StatID: Optional[int] = None
    Updated: Optional[str] = None
    Wins: Optional[float] = None


class Race(BaseModel):
    ActualLaps: Optional[int] = None
    Broadcast: Optional[str] = None
    Canceled: Optional[bool] = None
    Created: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    IsInProgress: Optional[bool] = None
    IsOver: Optional[bool] = None
    Name: Optional[str] = None
    PoleWinnerID: Optional[int] = None
    RaceID: Optional[int] = None
    RescheduledDateTime: Optional[str] = None
    RescheduledDay: Optional[str] = None
    ScheduledLaps: Optional[int] = None
    Season: Optional[int] = None
    SeriesID: Optional[int] = None
    SeriesName: Optional[str] = None
    Track: Optional[str] = None
    Updated: Optional[str] = None
    WinnerID: Optional[int] = None


class RaceResult(BaseModel):
    DriverRaces: Optional[List[DriverRace]] = None
    Race_1: Optional[Race] = Field(None, alias='Race')


class Series(BaseModel):
    Name: Optional[str] = None
    SeriesID: Optional[int] = None


class FieldFormatDriverRaceProjectionsRaceidGetResponse(
    RootModel[List[DriverRaceProjection]]
):
    root: List[DriverRaceProjection]


class Format(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatDriversGetResponse(RootModel[List[Driver]]):
    root: List[Driver]


class FieldFormatRacesSeasonGetResponse(RootModel[List[Race]]):
    root: List[Race]


class FieldFormatSeriesGetResponse(RootModel[List[Series]]):
    root: List[Series]
